[tool.poetry]
name = "stock-bot"
version = "0.0.1"
description = ""
authors = ["Andrea Scorza"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
python-dotenv = "^1.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
